# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Nginx | Debian | Install HTTPS transport.'
  become: yes
  apt:
    name: 'apt-transport-https'
    state: 'present'
  when: 'ansible_os_family == "Debian"'

- name: 'Nginx | Debian | Add launchpad PPA.'
  become: yes
  apt_repository:
    repo: '{{ nginx_ppa }}'
    update_cache: yes
  when: 'ansible_os_family == "Debian" and nginx_ppa | default(None) != None'

- name: 'Nginx | Debian | Update repository key.'
  become: yes
  apt_key:
    url: '{{ nginx_repo_key_url }}'
    state: '{{ nginx_repo_state }}'
  register: 'nginx_key'
  when: 'ansible_os_family == "Debian"'

- name: 'Nginx | Debian | Update repository list.'
  become: yes
  apt_repository:
    repo: '{{ nginx_repo_url }}'
    state: '{{ nginx_repo_state }}'
    filename: 'nginx'
  register: 'nginx_list'
  when: 'ansible_os_family == "Debian"'

- name: 'Nginx | Debian | Update APT cache.'
  become: yes
  apt:
    update_cache: yes
  when: 'ansible_os_family == "Debian" and (nginx_key.changed or nginx_list.changed)'

- name: 'Nginx | RedHat | Remove absent repository.'
  become: yes
  file:
    path: '/etc/yum.repos.d/{{ nginx_repo_uid }}.repo'
    state: 'absent'
  register: 'nginx_repo_removed'
  when: 'ansible_os_family == "RedHat" and nginx_repo_state | default("present") == "absent"'

- name: 'Nginx | RedHat | Add present repository.'
  become: yes
  template:
    src: 'yum.repo.j2'
    dest: '/etc/yum.repos.d/{{ nginx_repo_uid }}.repo'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'nginx_repo_added'
  when: 'ansible_os_family == "RedHat" and nginx_repo_state | default("present") == "present"'

- name: 'Nginx | Debian | Install Curl Python package.'
  become: yes
  apt:
    pkg: 'python-pycurl'
    state: 'present'
  when: 'ansible_os_family == "Debian"'

- name: 'Nginx | Debian | Install Nginx packages.'
  become: yes
  apt:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    cache_valid_time: '{{ item.cache_valid_time | default(omit) }}'
    deb: '{{ item.deb | default(omit) }}'
    default_release: '{{ item.default_release | default(omit) }}'
    dpkg_options: '{{ item.dpkg_options | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    install_recommends: '{{ item.install_recommends | default(omit) }}'
    purge: '{{ item.purge | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_cache: '{{ item.update_cache | default(omit) }}'
    upgrade: '{{ item.upgrade | default(omit) }}'
  with_items: '{{ nginx_packages }}'
  when: 'ansible_os_family == "Debian"'

- name: 'Nginx | RedHat | Install Nginx packages.'
  become: yes
  yum:
    name: '{{ item.name if item.version is not defined else item.name + "-" + item.version }}'
    conf_file: '{{ item.conf_file | default(omit) }}'
    disable_gpg_check: '{{ item.disable_gpg_check | default(omit) }}'
    disablerepo: '{{ item.disablerepo | default(omit) }}'
    enablerepo: '{{ item.enablerepo | default(omit) }}'
    exclude: '{{ item.exclude | default(omit) }}'
    list: '{{ item.list | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_cache: '{{ nginx_repo_removed.changed or nginx_repo_added.changed or item.update_cache | default(omit) }}'
  with_items: '{{ nginx_packages }}'
  when: 'ansible_os_family == "RedHat"'